### ISSUE TITLE
Installer hangs after extracting Tsumihoroboshi 7z archives

### ISSUE THREAD

**Issue by pmrowla** [07th-mod/Higurashi_Installer_WPF#20]
While installing the Tsumihoroboshi patch, the installer window hung on the progress bar for extracting Tsumihoroboshi-Movie.7z and became unresponsive. After letting it continue running for a couple of hours, I killed the installer and checked the logs, which indicate that the full patch installation finished, and the only real issue was related to the installer window.

I'm running:
- Windows 10
- Current Steam version of Tsumihoroboshi
- Installer v1.20

```
2018-09-29 13:41:39,507 [18] INFO  - All done, finishing in three seconds...
2018-09-29 13:41:39,507 [9] INFO  - Process has Finished with exit code 0!
2018-09-29 13:41:39,507 [1] INFO  - Finishing installation
2018-09-29 21:24:36,386 [1] ERROR - Outer Exception: Not enough quota is available to process this command
   at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

[PatcherLog.txt](https://github.com/07th-mod/Higurashi_Installer_WPF/files/2430630/PatcherLog.txt)

**Comment by drojf** [comment]
Thanks for giving a detailed bug report. I did some googling, and while i'm pretty sure this really is an issue with the installer, we haven't seen this issue before. it seems that this quota is global to windows, so possibly if some other program is using a chunk of it. That's not to say that our program isn't gobbling a huge amount of this quota (whatever it is...), it's just weird I haven't seen this issue before (then again, we don't get that many bug reports in general).

Did this problem occur more than once or just this one time? Also, I want to make sure that when you said "became unresponsive", you couldn't click on any buttons at all, and the whole program was frozen.

The other wierd thing is that the error is printed when you closed the installer, not when the program first froze. I'm Just worried that the actual error was something else, and the error message was from force quitting the installer.

**Comment by pmrowla** [comment]
I only tried installing Tsumihoroboshi this one time, but I've used a (pre-v1.20) version of the installer for the umineko answers arcs without any issues before on this same machine.

The entire program was frozen and I could not click on any buttons or do anything other than moving the window position, and I closed it via the windows task manager. Also, the window was frozen with the progress bar for extracting the movies 7z archive at around 40% if I remember correctly, but I didn't think to screenshot it at the time.

And again, as far as I can tell all of the patch archives were actually extracted properly.

**Comment by drojf** [comment]
Just an update on this issue - I wasn't really sure what to do, so I attempted a fresh install of Tsumi, and couldn't reproduce the issue.

Considering the amount of work to fix this issue vs the number of reports, I think it's better (for now) to just have a workaround for people who have this issue (well, it still technically installs OK but isn't very reassuring). 

If you consistently get this issue, you can use the "Manual Mode" option on the installer. This will download the correct batch file etc, but will notify you to run the batch file manually (by showing the batch file and asking you to double click).

I will leave this issue open so we can track how many reports of this issue we get. If we get more in the future, I can try and fix it.
