### ISSUE TITLE
"Could not create SSL/TLS secure channel." error for some users

### ISSUE THREAD

**Issue by drojf** [07th-mod/Higurashi_Installer_WPF#4]
A user reported a SSL/TLS error. The log is shown below:

```
2018-05-28 18:25:20,421 [1] INFO  - clicked onikakushi
2018-05-28 18:25:20,476 [1] INFO  - Resizing window
2018-05-28 18:25:20,479 [1] INFO  - Changed chapter
2018-05-28 18:25:22,455 [1] INFO  - Checking if path is valid
2018-05-28 18:25:25,802 [1] INFO  - Correct path selected
2018-05-28 18:25:34,760 [1] INFO  - Confirmation grid
2018-05-28 18:25:34,763 [1] INFO  - Constructing the patcher
2018-05-28 18:25:34,765 [1] INFO  - Chapter: onikakushi
2018-05-28 18:25:34,767 [1] INFO  - Install path: F:\SteamLibrary\steamapps\common\Higurashi When They Cry\HigurashiEp01_Data\temp
2018-05-28 18:25:37,786 [1] INFO  - Starting the installer
2018-05-28 18:25:37,792 [1] INFO  - Downloading install bat and creating temp folder
2018-05-28 18:25:37,792 [1] INFO  - Downloading install.bat
2018-05-28 18:25:45,195 [1] INFO  - Downloading resources.zip
2018-05-28 18:25:45,411 [1] INFO  - System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Higurashi_Installer_WPF.Utils.<DownloadResources>d16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Higurashi_Installer_WPF.MainWindow.<Confirm_Click>d17.MoveNext()
```

Rather than actually fixing it, it may be easier to bundle the 7zip and aria2c directly in the .exe (if it's easy to do):

https://stackoverflow.com/questions/526397/how-to-store-files-in-an-exe

Also it should be noted that it doesn't happen on all machines (not on my machine, at least). Possibly because there is a "SystemDefault" option for the system.net.securityprotocoltype value, which is different on different machines (see https://msdn.microsoft.com/en-us/library/system.net.securityprotocoltype(v=vs.110).aspx). I guess @ItaloKnox and others would know more about it since they had to deal with it previously.

**Comment by ItaloKnox** [comment]
This seems to be related to Github rather than the installer itself. Seems to be the same issue we had when running powershell to generate the link for the latest patch (InvokeWebRequest, see the dev wiki if you are interested). My bet is that the method used in C# relies on the same kind of connection. I don't know the specifics, but I think you're on the right track about this. Github nitpicks a lot in regards to how you download files, might be entirely random or the reason might be hidden somewhere.

Instead of making the .exe bigger, I just hosted the dependencies in my server. This should fix the issue until we decide what we are going to do about the new server.

Here: http://nijino-yu.me/ddl/dependencies.zip
Just change the location in the .exe and the issue should be mitigated.

**Comment by drojf** [comment]
oh ok I can do that easily, I'll just do that when i get home (if vocal doesn't beat me to it)

**Comment by ItaloKnox** [comment]
It's midnight over here so there's a chance he is sleeping right now (and also reminds me to go sleep already). 🤣

**Comment by drojf** [comment]
it's done. we could theoretically try both git and your server, and take the one which works, but I didn't do that for now. I just replaced the link.
